# print(5+6)
# print(5-6)
# print(5*6)
# print(15/6)
# print(17//6)
# print(15%6)
# print(5**4)
# print(2**4)

firstValue = input("Enter First Value : ")
secondValue = input("Enter Second Value : ")
# operator = input("Enter Operator : ")

# if operator == "+" :
print("Value is : ", int(firstValue) + int(secondValue))
print("Value is : ", int(firstValue) - int(secondValue))
print("Value is : ", int(firstValue) * int(secondValue))
print("Value is : ", int(firstValue) / int(secondValue))
print("Value is : ", int(firstValue) // int(secondValue))
print("Value is : ", int(firstValue) % int(secondValue))
print("Value is : ", int(firstValue) ** int(secondValue))
